<?php


namespace app\admin\controller;


use think\Controller;

class Base extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (cookie('admin_username')) {
            $res = db('admin_user')->where('token', cookie('admin_token'))->find();
            $this->assign('admin', $res);
        } else {
            $res = 0;
        }
        if (!$res) {
            $this->redirect('/admin/login');
        }
    }
}